### PR TITLE
mastery exercise submission

### PR DESCRIPTION
**Pull request by Zippoffer**

### CODE REVIEW

**Comment by Zippoffer** [comment]
@c-stein hey! I think it's ready for a look

**Comment by Zippoffer** [comment]
@morecallan helloooo!

**Comment by morecallan** [comment]
@Zippoffer DIGGING this submission. 

-**CoolPoints** for es6 destructuring, efficient use of split and map, solid stream pipeline and clearly organized code.

Before Next Review:
-Take a look at the project instructions on a usage statement.
-Make sure you are only including the const you need per file. 
-Make sure your variable names are super clear so another developer could open this up and know what is going on each step of the way. 

Let us know if you have any questions about it!

**Comment by Zippoffer** [comment]
@c-stein made some changes!

**Comment by C-Stein** [comment]
Changes look good, especially the comments. However, the test cases aren't returning anything. See if you can locate the problem, but feel free to come ask if you get stuck.

**Comment by C-Stein** [comment]
👍

**Pull request merged**
